inventory/urls.py
from django.conf.urls import url

from .views import (
    get_price_api,
)

app_name = 'inventory'

urlpatterns = [
    url(r'^price/$', get_price_api, name='part_price'),
]

search/urls.py
from django.conf.urls import url
from .views import SearchOrderView

app_name = 'search'

urlpatterns = [
    url(r'^$', SearchOrderView.as_view(), name='query'),
]

task_orders/urls.py
from django.urls import path

from .views import (
    TaskCreateView,
)

app_name = 'task_orders'

urlpatterns = [
    path('create/', TaskCreateView.as_view(), name='create'),
    
]

truckshop/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView
)

from accounts.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("work_orders.urls")),
    path('main/order/', include("search.urls")),
    path('main/task/', include("task_orders.urls")),
    path('main/parts/', include("inventory.urls")),
    path('account/', include("accounts.urls")),
    path('', LoginView.as_view(
        template_name='accounts/login.html',
        authentication_form=LoginForm), name='login'
    ),
]

work_orders/urls.py
from django.urls import path

from .views import (
    MainView, TimeCardView, clock_in,
    clock_out, start_or_end_task,
    WorkOrderUpdateView, WorkOrderCreateView,
    task_time_labor_update_api, load_trucks
)

from task_orders.views import (
    TaskUpdateView, TaskDeleteView, AddPartsCreateView,
    PartUpdateView, PartDeleteView,
)

app_name = 'work_orders'

urlpatterns = [
    path('', MainView.as_view(), name='index'),
    path('ajax/load/trucks/', load_trucks, name='ajax_load_trucks'),
    path('create/', WorkOrderCreateView.as_view(), name='create'),
    path('clockin/', clock_in, name='clockin'),
    path('clockout/', clock_out, name='clockout'),
    path('start/', start_or_end_task, name='start_or_end'),
    path('timecard/', TimeCardView.as_view(), name='time_card'),
    path('order/<slug:slug>/', WorkOrderUpdateView.as_view(), name='detail'),

    # task 
    path('task/<int:pk>/', TaskUpdateView.as_view(), name='update_task'),
    path('task/delete/<int:pk>/', TaskDeleteView.as_view(), name='delete_task'),
    path('update/timelabor/', task_time_labor_update_api, name='update_task_time_labor_ajax'),
    path('order/task/<int:pk>/add/part/', AddPartsCreateView.as_view(), name='add_part'),
    path('update/part/<int:pk>/', PartUpdateView.as_view(), name='update_part'),
    path('delete/part/<int:pk>/<int:id>/', PartDeleteView.as_view(), name='delete_part'),

    #
]

task_orders/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import (
    CreateView, UpdateView,
    DeleteView
)

from django.contrib import messages

from work_orders.forms import TaskForm, PartsByTaskForm
from inventory.models import Part
from work_orders.models import Task, PartsByTask, WorkOrder


class TaskCreateView(CreateView):
    template_name = 'task_orders/task_detail.html'
    queryset = Task.objects.all()
    form_class = TaskForm

    def get_initial(self):
        initial_data = super(TaskCreateView, self).get_initial()
        work_order = WorkOrder.objects.get(
            id=self.request.session.get("work_order_id", None))
        initial_data['work_order'] = work_order
        return initial_data

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        task = self.kwargs.get('pk')
        parts = PartsByTask.objects.filter(task=task)

        context = {
            "parts": parts,
            "task_pk": 0,
        }

        context.update(kwargs)
        return super().get_context_data(**context)

    def get_success_url(self, **kwargs):
        urls = reverse("work_orders:update_task", kwargs={
            "pk": self.object.id})
        return urls


class TaskUpdateView(UpdateView):
    template_name = 'task_orders/task_detail.html'
    queryset = Task.objects.all()
    form_class = TaskForm

    def get_context_data(self, **kwargs):
        task = self.kwargs.get('pk')
        parts = PartsByTask.objects.filter(task=task)

        context = {
            "parts": parts,
            "task_pk": self.kwargs.get('pk'),
        }

        context.update(kwargs)
        return super().get_context_data(**context)

    def get_success_url(self, **kwargs):
        task = Task.objects.get(id=self.kwargs.get('pk'))
        url = reverse("work_orders:detail", kwargs={
                      "slug": task.work_order.slug})
        return url


class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete_form.html'
    success_message = 'Success: Task was deleted.'

    def get_success_url(self, **kwargs):
        task = Task.objects.get(id=self.kwargs.get('pk'))
        url = reverse("work_orders:detail", kwargs={
                      "slug": task.work_order.slug})
        return url

    def get_context_data(self, **kwargs):
        # Modal title
        context = {
            "message": "Are you sure you want to delete this task",
            "title": "Delete task"
        }
        context.update(kwargs)
        return super(TaskDeleteView, self).get_context_data(**context)


class AddPartsCreateView(CreateView):
    template_name = 'task_orders/parts_form.html'
    form_class = PartsByTaskForm
    success_message = 'Success: Part was added.'
    task_id = 0

    def dispatch(self, request, *args, **kwargs):
        self.task_id = self.kwargs.get('pk')
        return super(AddPartsCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # check if the part is in the task
        part = form.cleaned_data['part']
        quantity = form.cleaned_data['quantity']
        obj_part = Part.objects.get(part_number=part)
        task = Task.objects.get(pk=self.task_id)

        obj = form.save(commit=False)
        obj.task = task
        obj.operation = 'Add'
        return super(AddPartsCreateView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        url = reverse("work_orders:update_task", kwargs={"pk": self.task_id})
        return url

    def get_context_data(self, **kwargs):
        # Modal title
        context = {
            "task": self.task_id,
            "button": "Add"
        }
        context.update(kwargs)
        return super().get_context_data(**context)


class PartUpdateView(UpdateView):

    model = PartsByTask
    template_name = 'task_orders/parts_form.html'
    form_class = PartsByTaskForm
    success_message = 'Success: Part was updated.'
    obj_part = dict()
    partbytask_id = 0

    def dispatch(self, request, *args, **kwargs):
        self.partbytask_id = self.kwargs.get('pk')
        self.obj_part = PartsByTask.objects.get(id=self.partbytask_id)
        return super(PartUpdateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        part = form.cleaned_data['part']
        quantity = form.cleaned_data['quantity']

        obj = form.save(commit=False)
        obj.operation = 'Update'
        return super(PartUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        # Modal title
        context = {
            "partbytask": self.partbytask_id,
            "task": self.obj_part.task.id,
            "button": "Update"
        }
        context.update(kwargs)
        return super(PartUpdateView, self).get_context_data(**context)

    def get_success_url(self, **kwargs):
        pk = self.kwargs.get('pk')
        qs = PartsByTask.objects.get(pk=pk)
        url = reverse("work_orders:update_task", kwargs={"pk": qs.task.pk})
        return url


class PartDeleteView(DeleteView):
    model = PartsByTask
    template_name = 'delete_form.html'
    success_message = 'Success: Part was deleted.'

    def get_success_url(self, **kwargs):
        pk = self.kwargs.get('id')
        url = reverse("work_orders:update_task", kwargs={"pk": pk})
        return url

    def get_context_data(self, **kwargs):
        # Modal title
        context = {
            "message": "Are you sure you want to delete this part",
            "title": "Delete part"
        }
        context.update(kwargs)
        return super(PartDeleteView, self).get_context_data(**context)

task_orders/templates/task_orders/delete_part_form.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete part</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>Are you sure you want to delete this part
      <strong>{{ object.part }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>

</form>

task_orders/templates/task_orders/parts_form.html
<!--Form for Add and edit part to task -->
{% load widget_tweaks %}
<div class="modal-dialog modal-lg">
  <div class="modal-content">
      {% if partbytask %}
      <form method="POST"  class="parts_task" action="{% url 'work_orders:update_part' partbytask %}" data-endpoint="{% url 'inventory:part_price' %}" data-task="{{ task }}" data-partbytask="{{ partbytask }}">
      {% else %}
      <form method="POST"  class="parts_task" action="{% url 'work_orders:add_part' task %}" data-endpoint="{% url 'inventory:part_price' %}" data-task="{{ task }}">
      {% endif %}
          {% csrf_token %}
          <div class="col-xl-12 col-md-12 mb-12">
          {% if obj %}
               {% firstof "warning" as color %} <!-- create variables in template. -->
          {% else %}
              {% firstof "success" as color %}
          {% endif %}
           <div class="card border-left-{{ color }} shadow h-100 py-2">
              <div class="card-body">
                  <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                          {% if partbytask%} Edit {% else %} Add {% endif %} Parts  
                      </div>
                      <div class="dropdown-divider"></div>
                      
                      <div id= "errors" class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
                        {% for error in form.non_field_errors %}
                          {{ error }}
                        {% endfor %}
                      </div>
            
                      {% for field in form %}
                        <div class="form-group">
                          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                          {{field}}<span class="{{ field.label }}"></span>
                          <div class="{% if field.errors %} invalid{% endif %}">
                            {% for error in field.errors %}
                            <br>
                              <p class="help-block">{{ error }}</p>
                            {% endfor %}
                          </div>
                        </div>
                      {% endfor %}
                      
                      </div>                    
                  <div class="dropdown-divider"></div>
                  </div>
                  <div class="col-auto">
                    <div class="col">
                      <button id="save" type="submit" class="btn btn-primary"><span class="fa fa-save"></span> Save</button>
                      <button type="button" class="btn btn-danger" onclick="return close_modal()">
                          Cancel
                      </button>
                    </div>
                  </div>
                  </div>
              </div>
          </div>
      </form>
  </div>
</div>

task_orders/templates/task_orders/task_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object %}
  {% firstof 'Edit Task' as title %}
{% else %}
  {% firstof 'New Task' as title %}
{% endif %}
<!-- Page Header -->
<div class="page-header row no-gutters py-4">
	<div class="col-12 col-sm-4 text-center text-sm-left mb-4 mb-sm-0">
		<span class="text-uppercase page-subtitle">Tasks</span>
		<h3 class="page-title">{{ title }}</h3>
	</div>
</div>
<!-- End Page Header -->
<div class="col col-lg-12 col-md-12 col-sm-12 mb-4 py-4">
  <div class="card card-small h-100">
    <div class="card-header border-bottom">
      <h6 class="m-0">Work order: 
          <span class="badge badge-primary">
				{{ request.session.work_order_slug }}
          </span>
      </h6>
      <div class="block-handle"></div>
    </div>
    <div class="card-body pt-0">
		<form method="POST" data-endpoint="{% url 'work_orders:update_task_time_labor_ajax' %}" class="task-form" task-pk="{{task_pk}}"> <!-- check for error -->
          {% csrf_token %}
          {{ form.work_order.as_hidden }}
          <div class="row border-bottom py-2 bg-light">
              <div class="col-12 col-sm-6 d-flex mb-2 mb-sm-0">
                <div class="btn-group btn-group-sm btn-group-toggle d-flex my-auto mx-auto mx-sm-0" data-toggle="buttons">
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div id="sessions-overview-date-range" class="input-daterange input-group input-group-sm my-auto ml-auto mr-auto ml-sm-auto mr-sm-0" style="max-width: 150px;">
                    <button type="submit" class="btn btn-primary btn-sm float-right" name="save">Save</button>
                    <a href="{% url 'work_orders:detail' request.session.work_order_slug %}" class="btn btn-danger btn-sm float-right">Cancel</a>
                </div>
              </div>
            </div>
            <div id="analytics-overview-sessions-legend"></div>
          <!-- Form structure -->
          <div class="row">
              <!-- start left -->
              <div class="col-6 py-4">
                  <!-- left header -->
                  <div class="form-group row">
                      <label for="inputTitle" class="col-sm-3 col-form-label">Title:</label>
                      <div class="col-sm-9">
                          {{ form.title }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="inputDescription" class="col-sm-3 col-form-label">Description:</label>
                      <div class="col-sm-9">
                          {{ form.description }}
                      </div>
                  </div>
                  <!-- end header -->
              </div>
              <!-- end left -->
              <!-- start right -->
              <div class="col-1"></div>
              <div class="col-5 py-4">				  
					<div class="form-group row">
						<label for="inputStatus" class="col-sm-3 col-form-label">Status:</label>
						<div class="col-sm-9">
							{{ form.status }}
						</div>
					</div>
					<div class="form-group row">
						<label for="inputMechanic" class="col-sm-3 col-form-label">Mechanic:</label>
						<div class="col-sm-9">
							{{ form.mechanic }}
						</div>
					</div>
					<div class="form-group row">
						<label for="inputTime" class="col-sm-3 col-form-label">Time labor:</label>
						<div class="col-sm-9">
              <!-- {% if task_pk == 0 %}
                <fieldset disabled="disabled">
                  {{ form.time_labor }}
                </fieldset>
              {% else %} -->
                {{ form.time_labor }}
              <!-- {% endif %} -->
						</div>
					</div>
                    <div class="form-group row">
                      <label for="input_total_parts" class="col-sm-6 col-form-label">Total parts:</label>
                      <div class="col-sm-4">
						            {{ form.total_parts }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="input_total_labor" class="col-sm-6 col-form-label">Total labor:</label>
                      <div class="col-sm-4">
                          {{ form.total_labor }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="input_total_task" class="col-sm-6 col-form-label">Total task:</label>
                      <div class="col-sm-4">
							          {{ form.total_task }}
                      </div>
                  </div>
              </div>
              <!-- end right -->
          </div>
          <!-- start detail -->
      </form>
      <div class="row border-bottom py-2 bg-light">
          <div class="col-12 col-sm-6 d-flex mb-2 mb-sm-0">
            <div class="btn-group btn-group-sm btn-group-toggle d-flex my-auto mx-auto mx-sm-0" data-toggle="buttons">
                <h6 class="m-0">Parts Detail:</h6>
            </div>
          </div>
          <div class="col-12 col-sm-6">
            <div id="sessions-overview-date-range" class="input-daterange input-group input-group-sm my-auto ml-auto mr-auto ml-sm-auto mr-sm-0" style="max-width: 150px;">
			{% if task_pk == 0 %}
				<button type="button" class="btn btn-primary btn-sm float-right" disabled> New part <i class="fas fa-plus-square"></i></button>
			{% else %}
				<button type="button" onclick="return open_modal('{% url 'work_orders:add_part' task_pk %}')" class="btn btn-primary btn-sm float-right"> New part <i class="fas fa-plus-square"></i></button>
			{% endif %}
            </div>
          </div>
      </div>
      <form action="{% url 'work_orders:start_or_end' %}">
          <div class="row">
              <div class="col">
                  <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%">
                      <thead>
						<th scope="col">#</th>
						<th scope="col">Part #</th>
						<th scope="col">Quantity</th>
						<th scope="col">Price</th>
						<th scope="col">Subtotal</th>
						<th scope="col">Actions</th>
                      </thead>
                      <tbody>
						{% for part in parts %}
						<tr>
							<td scope="row">{{forloop.counter}}</td>
							<td>{{part.part}}</td>
							<td>{{part.quantity}}</td>
							<td>{{part.price}}</td>
							<td>{{part.subtotal}}</td>
							<td>
								<button type="button" class="update-part btn btn-sm btn-primary" onclick="return open_modal('{% url 'work_orders:update_part' part.pk %}')" ><i class="fas fa-edit"></i>
								</button>
								<button type="button" class="delete-part btn btn-sm btn-danger" data-id="{% url 'work_orders:delete_part' part.pk part.task.pk %}"><i class="fas fa-trash-alt"></i>
								</button>
							</td>
						</tr>							    
						{% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
          <!-- Fin Detalle -->
      </form>
    </div>
  </div>
</div>

<!-- Modal adding , Deleting task  -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
	<div class="modal-dialog modal-dialog-centered" role="document">
    	<div class="modal-content"></div>
  	</div>
</div>			  

{% endblock %}



{% block js %}i
<!-- <script>
	$(function () {
		// lauch modal add part button
		$(".js-add-part").each(function () {
			$(this).modalForm({formURL: $(this).data('id')});
		});

		// Update part button
		$(".update-part").each(function () {
			$(this).modalForm({formURL: $(this).data('id')});
		});

		// Delete part button
		$(".delete-part").each(function () {
			$(this).modalForm({formURL: $(this).data('id')});
		});

	});
</script> -->

<script src="{% static 'js/truckshop.js' %}"></script>
{% endblock %}