search/urls.py
from django.conf.urls import url
from .views import SearchOrderView

app_name = 'search'

urlpatterns = [
    url(r'^$', SearchOrderView.as_view(), name='query'),
]

task_orders/urls.py
from django.urls import path

from .views import (
    TaskCreateView,
)

app_name = 'task_orders'

urlpatterns = [
    path('create/', TaskCreateView.as_view(), name='create'),
    
]

truckshop/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView
)

from accounts.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("work_orders.urls")),
    path('main/order/', include("search.urls")),
    path('main/task/', include("task_orders.urls")),
    path('main/parts/', include("inventory.urls")),
    path('account/', include("accounts.urls")),
    path('', LoginView.as_view(
        template_name='accounts/login.html',
        authentication_form=LoginForm), name='login'
    ),
]

work_orders/urls.py
from django.urls import path

from .views import (
    MainView, TimeCardView, clock_in,
    clock_out, start_or_end_task,
    WorkOrderUpdateView, WorkOrderCreateView,
    task_time_labor_update_api, load_trucks
)

from task_orders.views import (
    TaskUpdateView, TaskDeleteView, AddPartsCreateView,
    PartUpdateView, PartDeleteView,
)

app_name = 'work_orders'

urlpatterns = [
    path('', MainView.as_view(), name='index'),
    path('ajax/load/trucks/', load_trucks, name='ajax_load_trucks'),
    path('create/', WorkOrderCreateView.as_view(), name='create'),
    path('clockin/', clock_in, name='clockin'),
    path('clockout/', clock_out, name='clockout'),
    path('start/', start_or_end_task, name='start_or_end'),
    path('timecard/', TimeCardView.as_view(), name='time_card'),
    path('order/<slug:slug>/', WorkOrderUpdateView.as_view(), name='detail'),

    # task 
    path('task/<int:pk>/', TaskUpdateView.as_view(), name='update_task'),
    path('task/delete/<int:pk>/', TaskDeleteView.as_view(), name='delete_task'),
    path('update/timelabor/', task_time_labor_update_api, name='update_task_time_labor_ajax'),
    path('order/task/<int:pk>/add/part/', AddPartsCreateView.as_view(), name='add_part'),
    path('update/part/<int:pk>/', PartUpdateView.as_view(), name='update_part'),
    path('delete/part/<int:pk>/<int:id>/', PartDeleteView.as_view(), name='delete_part'),

    #
]

work_orders/models.py
from decimal import Decimal
from django.db import models
from django.db.models import Sum
from django.db.models import Q
from django.db.models.signals import pre_save, post_save, post_delete
from django.conf import settings
from django.urls import reverse


from accounts.models import Client
from inventory.models import Part
from truck.models import Truck
from truckshop.utils import unique_work_order_number_generator

WORK_ORDER_STATUS = (
    ('quote', 'Quote'),
    ('dropped_off', 'Dropped Off'),
    ('in_process', 'In Process'),
    ('closed', 'Closed Work Order'),
    ('paid', 'Paid Work Order'),
)

TASK_STATUS = (
    ('no_assigned', 'No assigned'),
    ('in_process', 'In Process'),
    ('completed', 'Completed'),
)

User = settings.AUTH_USER_MODEL


class WorkOrderManager(models.Manager):
    # Looking on the different fields
    def search(self, query):
        lookups = (
            Q(number_order__contains=query) |
            Q(client__name__icontains=query) |
            Q(truck__fleet__contains=query)
        )

        obj = self.get_queryset().filter(
            lookups).distinct().order_by('-number_order')
        print(obj)
        return obj

    # Order query from the lastest

    def all(self):
        obj = self.get_queryset().order_by('-number_order')
        return obj


class TaskManager(models.Manager):
    # Getting the tasks that belongs to a user
    def get_by_user(self, request):
        user = request.user
        obj = self.get_queryset().filter(
            mechanic=user).order_by('-number_order', 'id')
        return obj

    # Order query from the lastest

    # def all(self, request):
    #     obj = self.get_queryset.all().order_by('-number_order')
    #     return obj


class WorkOrder(models.Model):
    number_order = models.PositiveIntegerField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE)
    slug = models.CharField(max_length=30, null=True, blank=True)
    total_parts = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    total_labor = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    total_work_order = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    status = models.CharField(
        max_length=150,
        choices=WORK_ORDER_STATUS,
        default='quotes')

    objects = WorkOrderManager()

    def __str__(self):
        return str(self.number_order)

    def get_absolute_url(self):
        return reverse("work_orders:detail", kwargs={"slug": self.slug})


def workorder_pre_save_receiver(sender, instance, *args, **kwargs):

    if not instance.number_order:
        instance.number_order = unique_work_order_number_generator(
            instance)
        instance.slug = str(instance.number_order)


pre_save.connect(workorder_pre_save_receiver, sender=WorkOrder)


class Task(models.Model):
    work_order = models.ForeignKey(WorkOrder, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.TextField()
    time_labor = models.DecimalField(max_digits=100, decimal_places=2)
    mechanic = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    total_parts = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    total_labor = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    total_task = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)

    status = models.CharField(
        max_length=150,
        choices=TASK_STATUS,
        default='no_assigned')

    objects = TaskManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("work_orders:update_task", kwargs={"pk": self.pk})


def pre_save_task_receiver(sender, instance, *args, **kwargs):
    work_order = WorkOrder.objects.get(id=instance.work_order.id)
    instance.total_parts = get_sum_total_parts_in_task(instance)
    instance.total_labor = Decimal(instance.time_labor) * Decimal(115.00)
    instance.total_task = instance.total_parts + instance.total_labor
    work_order.total_parts, work_order.total_labor, \
        work_order.total_work_order = get_sum_totals_task_in_work_order(
            work_order)
    work_order.save()


pre_save.connect(pre_save_task_receiver, sender=Task)


def post_delete_task_receiver(sender, instance, *args, **kwargs):
    work_order = WorkOrder.objects.get(id=instance.work_order.id)
    work_order.total_parts, work_order.total_labor, \
        work_order.total_work_order = get_sum_totals_task_in_work_order(
            work_order)
    work_order.save()


post_delete.connect(post_delete_task_receiver, sender=Task)


class PartsByTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    subtotal = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    operation = models.CharField(max_length=10, null=True, blank=True)

    class Meta:
        unique_together = ('task', 'part',)

    def __str__(self):
        return str(self.part)

    


def pre_save_partsbytask_receiver(sender, instance, *args, **kwargs):
    if instance.quantity > 0:
        instance.subtotal = instance.quantity * instance.part.price
        instance.price = instance.part.price

        part = Part.objects.get(id=instance.part.id)

        # add or remove to the available in part for add and update
        if instance.operation == "Add":
            part.available = part.available - instance.quantity

        if instance.operation == "Update":
            partbytask = PartsByTask.objects.get(id=instance.id)

            print("old:" + str(partbytask.quantity))
            print("new:" + str(instance.quantity))

            # Changing the part on the update
            if partbytask.part != instance.part:
                old_part = Part.objects.get(id=partbytask.part.id)
                old_part.available = old_part.available + partbytask.quantity
                old_part.save()
                part.available = part.available - instance.quantity

            else:
                # Updating only quantity
                part.available = calculate_available(
                    partbytask.quantity, instance.quantity, part.available)

        part.save()
    else:
        instance.subtotal = 0.00


pre_save.connect(pre_save_partsbytask_receiver, sender=PartsByTask)


def calculate_available(old_quantity, new_quantity, available):
    if old_quantity > new_quantity:
        available = available + \
            (old_quantity - new_quantity)
    elif old_quantity < new_quantity:
        available = available - \
            (new_quantity - old_quantity)
    return available


# update totals in task after delete part and part.available
def post_delete_partsbytask_receiver(sender, instance, *args, **kwargs):
    qs = Task.objects.get(id=instance.task.id)
    part = Part.objects.get(id=instance.part.id)

    qs.total_parts = get_sum_total_parts_in_task(qs)
    qs.total_labor = Decimal(qs.time_labor) * Decimal(115.00)
    qs.total_task = qs.total_parts + qs.total_labor
    qs.save()

    part.available = part.available + instance.quantity
    part.save()


post_delete.connect(post_delete_partsbytask_receiver, sender=PartsByTask)

# update totals in task after save


def post_save_partsbytask_receiver(sender, instance, *args, **kwargs):
    qs = Task.objects.get(pk=instance.task.pk)
    qs.total_parts = get_sum_total_parts_in_task(qs)
    qs.total_labor = Decimal(qs.time_labor) * Decimal(115.00)
    qs.total_task = qs.total_parts + qs.total_labor
    qs.save()


post_save.connect(post_save_partsbytask_receiver, sender=PartsByTask)


class MechachicTimeTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now=True)
    clock_in = models.BooleanField()


def get_sum_total_parts_in_task(instance):
    parts = PartsByTask.objects.filter(task=instance)
    if parts:
        out = parts.aggregate(Sum('subtotal'))
        return out["subtotal__sum"]
    else:
        return Decimal(0)


def get_sum_totals_task_in_work_order(work_order):
    tasks = Task.objects.filter(work_order=work_order)
    if tasks:
        out = tasks.aggregate(Sum('total_parts'))
        out1 = tasks.aggregate(Sum('total_labor'))
        out2 = tasks.aggregate(Sum('total_task'))

        return (out['total_parts__sum'],
                out1['total_labor__sum'],
                out2['total_task__sum']
                )
    else:
        return 0, 0, 0

work_orders/views.py
from datetime import date
from decimal import Decimal
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import (
    CreateView, UpdateView, TemplateView,
)


from .forms import WorkOrderForm

from .models import MechachicTimeTask, Task, WorkOrder
from timecard.models import TimeDay
from truckshop.utils import unique_work_order_number_generator
from truck.models import Truck


today = date.today()

# Redirect depend of the group for the user


class MainView(LoginRequiredMixin, TemplateView):

    def get(self, request, *args, **kwargs):
        user = request.user
        # verify that the user is mechanic
        if check_group(user, 'Mechanics'):
            return redirect('work_orders:time_card')
        else:
            return redirect('search:query')


class TimeCardView(LoginRequiredMixin, TemplateView):
    template_name = 'work_orders/index2.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TimeCardView, self).get_context_data(
            *args, **kwargs)

        # Getting registers of the tasks. For to the user mechanic
        task_obj = Task.objects.get_by_user(self.request)

        # Getting registers for today where the mechanic marked time
        timecard = TimeDay.objects.filter(
            user=self.request.user, time__contains=today).order_by('time')

        # Getting lastest register for the mechanic,
        # it can be when he clock in or clock out
        try:
            time = TimeDay.objects.latest('time')
        except TimeDay.DoesNotExist:
            time = None

        try:
            currency = MechachicTimeTask.objects.filter(
                user=self.request.user, time__contains=today).latest('time')
        except MechachicTimeTask.DoesNotExist:
            currency = None

        context = {
            'task': task_obj,
            'timecard': timecard,
            'time': time,
            'currency': currency,
        }
        return context

# Creating a work order
class WorkOrderCreateView(LoginRequiredMixin, CreateView):
    template_name = 'work_orders/work_order_form.html'
    model = WorkOrder
    form_class = WorkOrderForm

    def get_context_data(self, **kwargs):

        context = {
            "work_order_pk": 0,
        }

        context.update(kwargs)
        return super().get_context_data(**context)

    def get_success_url(self, **kwargs):
        urls = reverse("work_orders:detail", kwargs={
            "slug": self.object.slug})
        return urls


class WorkOrderUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'work_orders/work_order_form.html'
    model = WorkOrder
    form_class = WorkOrderForm

    def get_context_data(self, **kwargs):
        slug = self.kwargs.get('slug')
        work_order = WorkOrder.objects.get(slug=slug)
        tasks = Task.objects.filter(work_order=work_order).order_by("id")
        
        context = {
            "tasks": tasks,
        }
        self.request.session['work_order_id'] = work_order.id
        self.request.session['work_order_slug'] = work_order.slug
        context.update(kwargs)
        return super().get_context_data(**context)

    def get_success_url(self, **kwargs):
        url = reverse("work_orders:index")
        return url

def clock_in(request):
    TimeDay.objects.create(user=request.user, clock_in=True)
    return redirect('work_orders:index')


def clock_out(request):
    TimeDay.objects.create(user=request.user, clock_in=False)
    return redirect('work_orders:index')


def start_or_end_task(request):
    query = request.GET.get('q', None)
    query2 = request.GET.get('type', None)

    if query2 == 'start':
        clockin = True
    else:
        clockin = False

    if query is not None:
        task = Task.objects.get(id=query)
        MechachicTimeTask.objects.create(
            task=task, user=request.user, clock_in=clockin)
    return redirect('work_orders:index')


def check_group(user, name_group):
    if user.groups.filter(name=name_group).exists():
        return True
    else:
        return False


def task_time_labor_update_api(request):
    time_labor = request.GET.get("time_labor")
    task_pk = request.GET.get("task_pk")
    
    
    qs = Task.objects.get(pk=task_pk)
    qs.time_labor = time_labor
    qs.save()

    task_data = {
        "total_parts": qs.total_parts,
        "total_labor": qs.total_labor,
        "total_task": qs.total_task
    }
        #     }
        # else:
        #     total_labor = Decimal(time_labor) * 125
        #     task_data = {
        #         "total_parts": '0',
        #         "total_labor": total_labor,
        #         "total_task": total_labor
        #     }

    return JsonResponse(task_data)


def load_trucks(request):
    client_id = request.GET.get('client')
    trucks = Truck.objects.filter(
        client_id=client_id).order_by('fleet')
    print(trucks)
    return render(request, 'snippets/truck_dropdown_list_options.html', {
        'trucks': trucks
    })

work_orders/templates/work_orders/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Main{% endblock title %}
{% block css %}
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.dataTables.min.css" />
{% endblock %}
{% block content %}
		
<!-- Page Header -->
<div class="page-header row no-gutters py-4">
  <div class="col-12 col-sm-4 text-center text-sm-left mb-4 mb-sm-0">
    <span class="text-uppercase page-subtitle">Dashboard</span>
    <h3 class="page-title">Transaction History</h3>
  </div>
</div>
<!-- End Page Header -->
<!-- Transaction History Table -->
<table class="transaction-history d-none">
  <thead>
    <tr>
      <th>#</th>
      <th>Created</th>
      <th>Customer</th>
      <th>Truck</th>
      <th>Status</th>
      <th>Total</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td><a href="{{ item.get_absolute_url }}" title="work_order">{{ item.number_order }}</a></td>
      <td>{{ item.date }}</span>
      </td>
      <td>{{ item.client }}</td>
      <td>{{ item.truck }}</td>
      <td>
        <span class="text-warning">{{ item.status }}</span>
      </td>
      <td>
        <span class="text-success">${{ item.total_work_order }}</span>
      </td>
      <td>
        <div class="btn-group btn-group-sm" role="group" aria-label="Table row actions">
          <button type="button" class="btn btn-white">
            <i class="material-icons">&#xE870;</i>
          </button>
          <a href="{{ item.get_absolute_url }}" class="btn btn-white"><i class="material-icons">&#xE254;</i></a>
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<!-- End Transaction History Table -->


{% endblock content %}
{% block js %}
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
<script src="{% static 'js/app/app-transaction-history.1.3.1.js' %}"></script>
{% endblock %}

work_orders/templates/work_orders/task_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<form method="POST" data-endpoint="{% url 'work_orders:update_task_time_labor_ajax' %}" class="task-form" task-pk="{{task_pk}}">
				{% csrf_token %}
			  <div class="form-row justify-content-center">
				<div class="col-12 col-md-6 mx-auto py-5">
						Work Order: {{form.work_order}}
				</div>
			  </div>
			  <div class="form-row">
			  	<div class="card  col-md-6">
				  <div class="card-header">
				   Task
				  </div>
				  <div class="card-body">
				    <div class="form-group">
				      <label for="inputTitle">Title:</label>
				      {{form.title}}
				    </div>
				    <div class="form-group">
				      <label for="inputdescription">Description:</label>
				      {{form.description}}
				    </div>
				  </div>
			  	</div>

			  	<div class="card  col-md-3">
				  <div class="card-header">
				    Time
				  </div>
				  <div class="card-body">
				    <div class="form-group">
				      <label for="inputMechanic">Mechanic:</label>
				      {{form.mechanic}}
				    </div>
				    <div class="form-group">
				      <label for="inputTime">Time labor:</label>
				      {{form.time_labor}}
				    </div>
				  </div>
			  	</div>
			  	<div class="card  col-md-3">
				  <div class="card-header">
				    Totals
				  </div>
				  <div class="card-body">
				    <div class="form-group">
				      <label for="inputMechanic">Total parts:</label>
				      <span class="Totalparts">{{form.total_parts}}</span>
				    </div>
				    <div class="form-group">
				      <label for="inputTime">Total labor:</label>
				      <span class="Totallabor">{{form.total_labor}}</span>				      
				    </div>
				    <div class="form-group">
				      <label for="inputTime">Total task:</label>
				      {{form.total_task}}
				    </div>
				    <div class="form-group">				    	
				      <button type="submit" class="btn btn-primary float-right">Save</button>
				      <button type="button" class="btn btn-danger float-right">Cancel</button>
				    </div>
				  </div>
			  	</div>
			  </div>
			</form>
			
			  <div class="row mx-auto py-5">	
			  	<div class="col-md-12 ">
			  		<div class="card">
					  <div class="card-header">
					    Parts <button type="button" class="btn btn-primary btn-sm float-right js-add-part" data-id="{% url 'work_orders:add_part' task_pk %}"> New part <i class="fas fa-plus-square"></i></button>
					  </div>
					  	<div class="card-body">
				          	<table class="table">
							  <thead>
							  	<tr>
							      <th scope="col">#</th>
							      <th scope="col">Part #</th>
							      <th scope="col">Quantity</th>
							      <th scope="col">Price</th>
							      <th scope="col">Subtotal</th>
							      <th scope="col">Actions</th>
							    </tr>
							  </thead>
							  <tbody>
							  	{% for part in parts %}
							    <tr>
							      <td scope="row">{{forloop.counter}}</td>
							      <td>{{part.part}}</td>
							      <td>{{part.quantity}}</td>
							      <td>{{part.price}}</td>
							      <td>{{part.subtotal}}</td>
							      <td>
							      	<button type="button" class="update-part btn btn-sm btn-primary" data-id="{% url 'work_orders:update_part' part.pk %}"><i class="fas fa-edit"></i>
							      	</button>
							      	<button type="button" class="delete-part btn btn-sm btn-danger" data-id="{% url 'work_orders:delete_part' part.pk part.task.pk %}"><i class="fas fa-trash-alt"></i>
							      	</button>
							      </td>
							    </tr>							    
							    {% endfor %}
							  </tbody>
							</table>	
				    	</div>	
			  		</div>
			  	</div>			    				
			  </div> 
		</div>
	</div>
</div>

<!-- Modal adding , edit parts on the task  -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
	<div class="modal-dialog modal-dialog-centered" role="document">
    	<div class="modal-content"></div>
  	</div>
</div>			  

{% endblock %}



{% block js %}
<script>
	
	$(function () {
		// lauch modal add part button
    	$(".js-add-part").modalForm({formURL: $(this).data('id')});

    	// Update part button
	    $(".update-part").each(function () {
	      $(this).modalForm({formURL: $(this).data('id')});
	    });

	    // Delete part button
	    $(".delete-part").each(function () {
	      $(this).modalForm({formURL: $(this).data('id')});
	    });

	});
</script>

<script src="{% static 'js/truckshop.js' %}"></script>

{% endblock %}

work_orders/templates/work_orders/work_order_form.html
{% extends "base.html" %}

{% block content %}
{% if object %}
  {% firstof 'Edit Work Order' as title %}
{% else %}
  {% firstof 'New Work Order' as title %}
{% endif %}
<!-- Page Header -->
<div class="page-header row no-gutters py-4">
  <div class="col-12 col-sm-4 text-center text-sm-left mb-4 mb-sm-0">
    <span class="text-uppercase page-subtitle">Work Orders</span>
    <h3 class="page-title">{{ title }}</h3>
  </div>
</div>
<!-- End Page Header -->


<div class="col col-lg-12 col-md-12 col-sm-12 mb-4">
  <div class="card card-small h-100">
    <div class="card-header border-bottom">
      <h6 class="m-0">Work order: 
          <span class="badge badge-primary">
              {{ form.number_order.value }}
          </span>
      </h6>
      <div class="block-handle"></div>
    </div>
    <div class="card-body pt-0">
      <form method="POST"  id="workorderForm" class="work_order_form" data-trucks-url="{% url 'work_orders:ajax_load_trucks' %}">
          {% csrf_token %}
          {{ form.number_order.as_hidden }}
          <div class="row border-bottom py-2 bg-light">
              <div class="col-12 col-sm-6 d-flex mb-2 mb-sm-0">
                <div class="btn-group btn-group-sm btn-group-toggle d-flex my-auto mx-auto mx-sm-0" data-toggle="buttons">
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div id="sessions-overview-date-range" class="input-daterange input-group input-group-sm my-auto ml-auto mr-auto ml-sm-auto mr-sm-0" style="max-width: 150px;">
                    <button type="submit" class="btn btn-primary btn-sm float-right" name="save">Save</button>
                    <a href="{% url 'work_orders:index' %}" class="btn btn-danger btn-sm float-right">Cancel</a>
                </div>
              </div>
            </div>
            <div id="analytics-overview-sessions-legend"></div>
          <!-- Form structure -->
          <div class="row">
              <!-- start left -->
              <div class="col-6 py-4">
                  <!-- left header -->
                  <div class="form-group row">
                      <label for="client" class="col-sm-2 col-form-label">Customer:</label>
                      <div class="col-sm-10">
                          {{ form.client }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="truck" class="col-sm-2 col-form-label">Vehicle:</label>
                      <div class="col-sm-10">
                          {{ form.truck }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="status" class="col-sm-2 col-form-label">Status:</label>
                      <div class="col-sm-10">
                          {{ form.status }}
                      </div>
                  </div>
                  <!-- end header -->
              </div>
              <!-- end left -->
              <!-- start right -->
              <div class="col-1"></div>
              <div class="col-5 py-4">
                  <div class="form-group row">
                      <label for="id_total_parts" class="col-sm-6 col-form-label">Total parts:</label>
                      <div class="col-sm-4">
                        {{ form.total_parts }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="id_total_labor" class="col-sm-6 col-form-label">Total labor:</label>
                      <div class="col-sm-4">
                          {{ form.total_labor }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="id_total_work_order" class="col-sm-6 col-form-label">Total work order:</label>
                      <div class="col-sm-4">
                          {{ form.total_work_order }}
                      </div>
                  </div>
              </div>
              <!-- end right -->
          </div>
          <!-- start detail -->
      </form>
      <div class="row border-bottom py-2 bg-light">
          <div class="col-12 col-sm-6 d-flex mb-2 mb-sm-0">
            <div class="btn-group btn-group-sm btn-group-toggle d-flex my-auto mx-auto mx-sm-0" data-toggle="buttons">
                <h6 class="m-0">Tasks Detail:</h6>
            </div>
          </div>
          <div class="col-12 col-sm-6">
            <div id="sessions-overview-date-range" class="input-daterange input-group input-group-sm my-auto ml-auto mr-auto ml-sm-auto mr-sm-0" style="max-width: 150px;">
              {% if work_order_pk == 0 %}
					    	<button type="button" class="btn btn-primary btn-sm float-right" disabled> New task <i class="fas fa-plus-square"></i></button>
					    {% else %}
					    	<a href="{% url 'task_orders:create' %}" title=""><button type="button" class="btn btn-primary btn-sm float-right"> New task <i class="fas fa-plus-square"></i></button></a>
					    {% endif %}
            </div>
          </div>
      </div>
      <form action="{% url 'work_orders:start_or_end' %}">
          <div class="row">
              <div class="col">
                  <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%">
                      <thead>
                          <th>#</th>
                          <th>Task</th>
                          <th>Mechanic</th>
                          <th>Total Hours</th>
                          <th>Total ($)</th>
                          <th>Status</th>
                          <th>Actions</th>
                      </thead>
                      <tbody>
                          {% for task in tasks %}
                          <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a href="{{task.get_absolute_url}}" data-toggle="popover" title="{{ task.title }}" data-content="{{task.description}}">{{ task.title }}</a></td>
                            <td>{{ task.mechanic }}</td>
                            <td>( {{ task.time_labor }} )</td>
                            <td>( {{ task.total_task }} )</td>
                            <td> {{ task.get_status_display }} </td>
                            <td>
                              <a href="{{ task.get_absolute_url }}" class="btn btn-sm btn-primary"><i class="fas fa-edit"></i></a>
                              <button type="button" class="delete-task btn btn-sm btn-danger" data-id="{% url 'work_orders:delete_task' task.id %}"><i class="fas fa-trash-alt"></i>
                              </button>							      
                          </tr>							    
                          {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
          <!-- Fin Detalle -->
      </form>
    </div>
  </div>
</div>


{% endblock %}



{% block js %}
<script>
	$(function () {
	    // Delete task button
	    $(".delete-task").each(function () {
	      $(this).modalForm({formURL: $(this).data('id')});
	    });
	});
</script>		 

<script>
    $("#id_client").change(function () {
      var url = $("#workorderForm").attr("data-trucks-url");  // get the url of the `load_trucks` view
      var clientId = $(this).val();  // get the selected client ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request ties/)
        data: {
          'client': clientId       // add the client id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_trucks` view function
          $("#id_truck").html(data);  // replace the contents of the truck input with the data that came from the server
        }
      });

    });
  </script>


{% endblock %}