search/urls.py
from django.conf.urls import url
from .views import SearchOrderView

app_name = 'search'

urlpatterns = [
    url(r'^$', SearchOrderView.as_view(), name='query'),
]

truckshop/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView
)

from accounts.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("work_orders.urls")),
    path('main/order/', include("search.urls")),
    path('main/task/', include("task_orders.urls")),
    path('main/parts/', include("inventory.urls")),
    path('account/', include("accounts.urls")),
    path('', LoginView.as_view(
        template_name='accounts/login.html',
        authentication_form=LoginForm), name='login'
    ),
]

search/views.py
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from work_orders.models import WorkOrder
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



class SearchOrderView(LoginRequiredMixin, ListView):
    template_name = "work_orders/index.html"
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q', None)
        if query is not None:
            return WorkOrder.objects.search(query)
        return WorkOrder.objects.all()

search/templates/search/snippets/search.html
<form method="GET" action="{% url 'search:query'%}" class="form my-2 my-lg-0">
	<div class="input-group">
		<input class="form-control" type="text" placeholder="Search" name="q" aria-label="Search" value="{{request.GET.q }}">
		<span class="input-group-btn">
			<button class="btn btn-outline-success" type="submit">Search</button>	
		</span>
	</div>
</form>