accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView
)


app_name = 'account'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
]

search/urls.py
from django.conf.urls import url
from .views import SearchOrderView

app_name = 'search'

urlpatterns = [
    url(r'^$', SearchOrderView.as_view(), name='query'),
]

truckshop/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView
)

from accounts.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("work_orders.urls")),
    path('main/order/', include("search.urls")),
    path('main/task/', include("task_orders.urls")),
    path('main/parts/', include("inventory.urls")),
    path('account/', include("accounts.urls")),
    path('', LoginView.as_view(
        template_name='accounts/login.html',
        authentication_form=LoginForm), name='login'
    ),
]

work_orders/urls.py
from django.urls import path

from .views import (
    MainView, TimeCardView, clock_in,
    clock_out, start_or_end_task,
    WorkOrderUpdateView, WorkOrderCreateView,
    task_time_labor_update_api, load_trucks
)

from task_orders.views import (
    TaskUpdateView, TaskDeleteView, AddPartsCreateView,
    PartUpdateView, PartDeleteView,
)

app_name = 'work_orders'

urlpatterns = [
    path('', MainView.as_view(), name='index'),
    path('ajax/load/trucks/', load_trucks, name='ajax_load_trucks'),
    path('create/', WorkOrderCreateView.as_view(), name='create'),
    path('clockin/', clock_in, name='clockin'),
    path('clockout/', clock_out, name='clockout'),
    path('start/', start_or_end_task, name='start_or_end'),
    path('timecard/', TimeCardView.as_view(), name='time_card'),
    path('order/<slug:slug>/', WorkOrderUpdateView.as_view(), name='detail'),

    # task 
    path('task/<int:pk>/', TaskUpdateView.as_view(), name='update_task'),
    path('task/delete/<int:pk>/', TaskDeleteView.as_view(), name='delete_task'),
    path('update/timelabor/', task_time_labor_update_api, name='update_task_time_labor_ajax'),
    path('order/task/<int:pk>/add/part/', AddPartsCreateView.as_view(), name='add_part'),
    path('update/part/<int:pk>/', PartUpdateView.as_view(), name='update_part'),
    path('delete/part/<int:pk>/<int:id>/', PartDeleteView.as_view(), name='delete_part'),

    #
]

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js h-100" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="A premium collection of beautiful hand-crafted Bootstrap 4 admin dashboard templates and dozens of custom components built for data-driven applications.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.3.1" href="{% static 'css/shards-dashboards.1.3.1.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/extras.1.3.1.min.css' %}">
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    {% block css %}{% endblock %}
  </head>
  <body class="h-100">
    <div class="container-fluid">
        <div class="row">
            {% block sidebar %}
              {% include 'sidebar.html' %}
            {% endblock sidebar %}
            <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
              {% block topbar %}
                  {% include 'topbar.html' %}
              {% endblock topbar %}
              <div class="main-content-container container-fluid px-4 mb-4">
                {% block content %}{% endblock content %}
              </div>
            </main>
        </div>
    </div>

    <!-- MODAL  -->

    <div class="modal fade" id="popup">

    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
    <script src="{% static 'js/extras.1.3.1.min.js' %}"></script>
    <script src="{% static 'js/shards-dashboards.1.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% block js %}{% endblock %}

    {% block control_modal %}
    <script>
      function open_modal(url)
      {
        $("#popup").load(url, function(){
          $(this).modal({
            backdrop: 'static',
            keyboard: false
          });
          $(this).modal('show');
        });
        return false;
      }

      function close_modal(url){
        $('#popup').modal('hide');
        return false;
      }

      function message(msg, color="green"){
        if (color == "success") {
          color = "green";
        }
        if (color == "error") {
          color = "red";
        }
        if (color == "warning"){
          color = "orange";
        }

        $.alert({
          title: "",
          theme: "material",
          type: color,
          content: msg
        });
     };

     {% if messages %}
      {% for message in messages %}
        message("{{ message }}", "{{ message.tags }}");
      {% endfor %}
     {% endif %}


    </script>
  {% endblock control_modal %}
  
  </body>
</html>

templates/delete_form.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{{ title }}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>{{ message }}
      <strong>{{ object }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>

</form>

templates/sidebar.html
{% load static %}
<!-- Main Sidebar -->
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
  <div class="main-navbar">
    <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
      <a class="navbar-brand w-100 mr-0" href="{% url 'work_orders:index' %}" style="line-height: 25px;">
        <div class="d-table m-auto">
          <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;" src="{% static 'img/shards-dashboards-logo.svg' %}" alt="Shards Dashboard">
          <span class="d-none d-md-inline ml-1">ETruckShop</span>
        </div>
      </a>
      <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
        <i class="material-icons">&#xE5C4;</i>
      </a>
    </nav>
  </div>
  <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
    <div class="input-group input-group-seamless ml-3">
      <div class="input-group-prepend">
        <div class="input-group-text">
          <i class="fas fa-search"></i>
        </div>
      </div>
      <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search">
    </div>
  </form>
  <div class="nav-wrapper">
    <h6 class="main-sidebar__nav-title">Work Orders</h6>
    <ul class="nav nav--no-borders flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'work_orders:index' %}">
          <i class="material-icons">&#xE889;</i>
          <span>Transaction History</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'work_orders:create' %}">
          <i class="material-icons">&#xE917;</i>
          <span>Create Work Order</span>
        </a>
      </li>
      <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
            <i class="material-icons">&#xE917;</i>
            <span>Work Orders</span>
          </a>
          <div class="dropdown-menu dropdown-menu-small">
            <a class="dropdown-item " href="">Create new</a>
          </div>
      </li> -->
    </ul>
    <h6 class="main-sidebar__nav-title">Accounts</h6>
    <ul class="nav nav--no-borders flex-column">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">
          <i class="material-icons">&#xE7FD;</i>
          <span>User Account</span>
        </a>
        <!-- <div class="dropdown-menu dropdown-menu-small">
          <a class="dropdown-item " href="user-profile.html">User Profile</a>
          <a class="dropdown-item " href="user-profile-lite.html">User Profile Lite</a>
          <a class="dropdown-item " href="edit-user-profile.html">Edit User Profile</a>
          <a class="dropdown-item " href="login.html">Login</a>
          <a class="dropdown-item " href="register.html">Register</a>
          <a class="dropdown-item " href="forgot-password.html">Forgot Password</a>
          <a class="dropdown-item " href="change-password.html">Change Password</a>
        </div> -->
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
          <i class="material-icons">&#xE2C7;</i>
          <span>File Managers</span>
        </a>
        <div class="dropdown-menu dropdown-menu-small">
          <a class="dropdown-item " href="file-manager-list.html">Files - List View</a>
          <a class="dropdown-item " href="file-manager-cards.html">Files - Cards View</a>
        </div>
      </li>
      
      <li class="nav-item">
        <a class="nav-link " href="calendar.html">
          <i class="material-icons">calendar_today</i>
          <span>Calendar</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="add-new-post.html">
          <i class="material-icons">note_add</i>
          <span>Add New Post</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="errors.html">
          <i class="material-icons">error</i>
          <span>Errors</span>
        </a>
      </li> -->
    </ul>
    <!-- <h6 class="main-sidebar__nav-title">Components</h6>
    <ul class="nav nav--no-borders flex-column">
      <li class="nav-item">
        <a class="nav-link " href="components-overview.html">
          <i class="material-icons">view_module</i>
          <span>Overview</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="tables.html">
          <i class="material-icons">table_chart</i>
          <span>Tables</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="components-blog-posts.html">
          <i class="material-icons">vertical_split</i>
          <span>Blog Posts</span>
        </a>
      </li>
    </ul>
    <h6 class="main-sidebar__nav-title">Layouts</h6>
    <ul class="nav nav--no-borders flex-column">
      <li class="nav-item">
        <a class="nav-link " href="header-navigation.html">
          <i class="material-icons">view_day</i>
          <span>Header Nav</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="icon-sidebar-nav.html">
          <i class="material-icons">&#xE251;</i>
          <span>Icon Sidebar</span>
        </a>
      </li>
    </ul> -->
  </div>
</aside>
		<!-- End Main Sidebar -->

templates/topbar.html
{% load static %}

{% block topbar %}
<div class="main-navbar sticky-top bg-white">
    <!-- Main Navbar -->
    <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
      <div class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">
      </div>
      <ul class="navbar-nav border-left flex-row ">
        <!-- <li class="nav-item border-right dropdown notifications">
          <a class="nav-link nav-link-icon text-center" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="nav-link-icon__wrapper">
              <i class="material-icons">&#xE7F4;</i>
              <span class="badge badge-pill badge-danger">2</span>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-small" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="#">
              <div class="notification__icon-wrapper">
                <div class="notification__icon">
                  <i class="material-icons">&#xE6E1;</i>
                </div>
              </div>
              <div class="notification__content">
                <span class="notification__category">Analytics</span>
                <p>Your website’s active users count increased by <span class="text-success text-semibold">28%</span> in the last week. Great job!</p>
              </div>
            </a>
            <a class="dropdown-item" href="#">
              <div class="notification__icon-wrapper">
                <div class="notification__icon">
                  <i class="material-icons">&#xE8D1;</i>
                </div>
              </div>
              <div class="notification__content">
                <span class="notification__category">Sales</span>
                <p>Last week your store’s sales count decreased by <span class="text-danger text-semibold">5.52%</span>. It could have been worse!</p>
              </div>
            </a>
            <a class="dropdown-item notification__all text-center" href="#"> View all Notifications </a>
          </div>
        </li> -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <img class="user-avatar rounded-circle mr-2" src="{% static 'img/avatars/0.jpg' %}" alt="User Avatar"> <span class="d-none d-md-inline-block">{{ request.user.username }}</span>
          </a>
          <div class="dropdown-menu dropdown-menu-small">
            <a class="dropdown-item" href="user-profile.html"><i class="material-icons">&#xE7FD;</i> Profile</a>
            <a class="dropdown-item" href="edit-user-profile.html"><i class="material-icons">&#xE8B8;</i> Edit Profile</a>
            <a class="dropdown-item" href="file-manager-cards.html"><i class="material-icons">&#xE2C7;</i> Files</a>
            <a class="dropdown-item" href="transaction-history.html"><i class="material-icons">&#xE896;</i> Transactions</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-danger" href="{% url 'account:logout' %}">
              <i class="material-icons text-danger">&#xE879;</i> Logout </a>
          </div>
        </li>
      </ul>
      <nav class="nav">
        <a href="#" class="nav-link nav-link-icon toggle-sidebar d-sm-inline d-md-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
          <i class="material-icons">&#xE5D2;</i>
        </a>
      </nav>
    </nav>
  </div> <!-- / .main-navbar -->
{% endblock topbar %}